#!/usr/bin/env bash
# Build a single-file executable with PyInstaller (from within the project folder).
# Includes the 'snd' folder and 'background.png' in the bundle.
#
# Usage:
#   chmod +x build_exe.sh
#   ./build_exe.sh
# Optionally pass a Python executable:
#   ./build_exe.sh /usr/bin/python3.11
set -e

PYTHON_cmd="${1:-python3}"

if [ ! -f "game.py" ]; then
  echo "Error: game.py not found in current directory. cd to the project folder and re-run."
  exit 1
fi

# Detect platform path separator for --add-data (PyInstaller uses ":" on Linux/macOS, ";" on Windows)
OSNAME="$(uname -s 2>/dev/null || echo unknown)"
if echo "$OSNAME" | grep -qiE "msys|mingw|cygwin|nt"; then
  SEP=";"
else
  SEP=":"
fi

echo "Using Python: $PYTHON_cmd"
echo "Detected platform: $OSNAME (PyInstaller data separator set to '$SEP')"

# Use venv if present (activate appropriate script for platform)
if [ -d "venv" ]; then
  echo "Activating local virtualenv..."
  if [ -f "venv/bin/activate" ]; then
    # POSIX
    # shellcheck disable=SC1091
    source venv/bin/activate
  elif [ -f "venv/Scripts/activate" ]; then
    # Windows (Git Bash / MSYS)
    # shellcheck disable=SC1091
    source venv/Scripts/activate
  fi
fi

echo "Upgrading pip tooling and installing PyInstaller..."
python -m pip install --upgrade pip setuptools wheel
python -m pip install --upgrade pyinstaller

# Ensure snd folder exists (it will be generated on first run if not)
if [ ! -d "snd" ]; then
  echo "Warning: 'snd' folder not found. It will be generated by the game on first run, but it's better to run the game once before bundling so the folder exists."
fi

# Assemble add-data arguments
ADD_DATA_ARGS=()
# include sound folder
ADD_DATA_ARGS+=(--add-data "snd${SEP}snd")
# include background image if present
if [ -f "background.png" ]; then
  ADD_DATA_ARGS+=(--add-data "background.png${SEP}.")
else
  echo "Note: background.png not found in project root. If you plan to include one, add it before building or the game will run without it."
fi

# Optionally include highscores.json so saved highscore persists in build dir (not strictly necessary)
if [ -f "highscores.json" ]; then
  ADD_DATA_ARGS+=(--add-data "highscores.json${SEP}.")
fi

echo "Running PyInstaller (this may take a minute)..."
# Remove previous build artifacts to avoid stale bundles
rm -rf build dist __pycache__ game.spec

# Run pyinstaller with the assembled add-data flags
pyinstaller --onefile --name space_dodger "${ADD_DATA_ARGS[@]}" game.py

echo
echo "PyInstaller finished."
if [ -f "dist/space_dodger" ]; then
  echo "Executable created: $(pwd)/dist/space_dodger"
elif [ -f "dist/space_dodger.exe" ]; then
  echo "Executable created: $(pwd)/dist/space_dodger.exe"
else
  echo "Build completed but expected output not found in dist/. Check PyInstaller output for errors."
fi

echo "Tip: When running the bundled executable, the game uses resource_path(...) to find bundled data (snd/ and background.png)."